- name: Setup Consul Client Agent and Vault Server
  hosts: 
    - tag_Name_consul
    - tag_Name_Vault
  become: yes
  vars:
    consul_version: "1.14.4"
    vault_version: "1.12.3"
    vault_private_ip: "{{ groups['tag_Name_Vault'] | map('extract', hostvars, ['private_ip_address']) | list }}"
    consul_servers: "{{ groups['tag_Name_consul'] | map('extract', hostvars, ['private_ip_address']) | list }}"

  tasks:
    - name: Debug Vault private IPs
      debug:
        msg: "{{ vault_private_ip }}"

    - name: Debug Consul Servers IPs
      debug:
        msg: "{{ consul_servers }}"

    - name: Install dependencies
      apt:
        name:
          - wget
          - unzip
        state: present

    - name: Download and install Consul
      shell: |
        wget https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip
        unzip consul_{{ consul_version }}_linux_amd64.zip
        mv consul /usr/local/bin/
        cp /usr/local/bin/consul /usr/bin/
        rm -f consul_{{ consul_version }}_linux_amd64.zip
      args:
        creates: /usr/local/bin/consul

    - name: Create Consul directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /usr/local/etc/consul
        - /var/consul/data

    - name: Create Consul client configuration
      copy:
        dest: /usr/local/etc/consul/consul_c1.json
        content: |
           {
            "server": false,
            "datacenter": "dc1",
            "node_name": "consul_c1",
            "data_dir": "/var/consul/data",
            "bind_addr": "{{ vault_private_ip[0] }}",  # Get the first Vault IP
            "client_addr": "127.0.0.1",
            "retry_join": {{ consul_servers | to_json }},  # Convert list to JSON format
            "log_level": "DEBUG",
            "enable_syslog": true,
            "acl_enforce_version_8": false
           }

    - name: Create Consul systemd service file
      copy:
        dest: /etc/systemd/system/consul.service
        content: |
          [Unit]
          Description=Consul server agent
          Requires=network-online.target
          After=network-online.target

          [Service]
          PIDFile=/var/run/consul/consul-server.pid
          PermissionsStartOnly=true
          ExecStart=/usr/local/bin/consul agent \
              -config-file=/usr/local/etc/consul/consul_c1.json \
              -pid-file=/var/run/consul/consul-server.pid
          ExecReload=/bin/kill -HUP $MAINPID
          KillMode=process
          KillSignal=SIGTERM
          Restart=on-failure
          RestartSec=42s

          [Install]
          WantedBy=multi-user.target

    - name: Start and enable Consul service
      systemd:
        name: consul
        state: started
        enabled: true

    - name: Download and install Vault
      shell: |
        wget https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip
        unzip vault_{{ vault_version }}_linux_amd64.zip
        mv vault /usr/local/bin/
        rm -f vault_{{ vault_version }}_linux_amd64.zip
      args:
        creates: /usr/local/bin/vault

    - name: Create Vault configuration directory
      file:
        path: /etc/vault
        state: directory
        mode: '0755'

    - name: Create Vault configuration
      copy:
        dest: /etc/vault/vault_server.hcl
        content: |
          listener "tcp" {
            address          = "0.0.0.0:8200"
            cluster_address  = "{{ vault_private_ip[0] }}:8201"  # Use the first Vault IP
            tls_disable      = "true"
          }
          storage "consul" {
            address = "127.0.0.1:8500"
            path    = "vault/"
          }
          api_addr = "http://{{ vault_private_ip[0] }}:8200"
          cluster_addr = "https://{{ vault_private_ip[0] }}:8201"
          ui = true

    - name: Create Vault systemd service file
      copy:
        dest: /etc/systemd/system/vault.service
        content: |
          [Unit]
          Description=Vault secret management tool
          Requires=network-online.target
          After=network-online.target

          [Service]
          PIDFile=/var/run/vault/vault.pid
          ExecStart=/usr/local/bin/vault server -config=/etc/vault/vault_server.hcl -log-level=debug
          ExecReload=/bin/kill -HUP $MAINPID
          KillMode=process
          KillSignal=SIGTERM
          Restart=on-failure
          RestartSec=42s
          LimitMEMLOCK=infinity

          [Install]
          WantedBy=multi-user.target

    - name: Start and enable Vault service
      systemd:
        name: vault
        state: started
        enabled: true
