---
- name: Configure Consul systemd service
  template:
    src: consul.service.j2
    dest: /etc/systemd/system/consul.service
  notify: restart consul

- name: Start and enable Consul service
  systemd:
    name: consul
    enabled: yes
    state: started
